---
title: "git_01"
author: "Celeste Meza"
date: "Summer 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

A boat beneath a sunny sky,  
Lingering onward dreamily  
In an evening of July —  

Children three that nestle near,  
Eager eye and willing ear,  



## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

I have been one acquainted with the night   
I have walked out in rain—and back in rain  
I have outwalked the furthest city light   

I have looked down the saddest city lane    
I have passed by the watchman on his beat  



## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  





## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Loveliests of trees, the cherry now  
Is hung with bloom along the bough,  
And stands about the woodland ride  
Wearing white for Eastertide   

Now, of my threescore years and ten,  
Twenty will not come again,  
And take from seventy springs a score,  
It only leaves me fifty more.  

And since to look at things in bloom  
Fifty springs are little room,  
About the woodlands I will go  
To see the cherry hung with snow.  




